name: Cypress Tests

on:

  schedule:
    - cron: '15 13 * * *' 
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run cypress:run

  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'

      - name: Install dependencies
        run: npm install

      - name: Generate Cucumber HTML report
        run: npm run generate-report || true

      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: reports/cucumber_report.html

